import React from "react";
import Link from 'next/link';
import { FiAlertTriangle, FiInfo } from "react-icons/fi";

export const metadata = {
  title: 'Disclaimer | NovuliSurvices',
  description: 'Accuracy disclaimer for NovuliSurvices tool outputs.',
};

export default function DisclaimerPage() {
  return (
    <div className="bg-bg-gray min-h-screen pt-32 pb-24">
      <div className="max-w-4xl mx-auto px-4">
        <div className="bg-white rounded-[2.5rem] p-10 md:p-16 shadow-2xl shadow-blue-900/[0.03] border border-border-light">
          <div className="w-20 h-20 bg-amber-50 rounded-3xl flex items-center justify-center mb-10 border border-amber-100">
            <FiAlertTriangle className="text-amber-500" size={40} />
          </div>
          
          <h1 className="text-4xl md:text-5xl font-display font-bold text-primary mb-8 tracking-tight">Accuracy Disclaimer</h1>
          
          <div className="prose prose-blue prose-lg text-secondary max-w-none">
            <p className="text-xl font-medium text-primary mb-8 leading-relaxed">
              The tools provided by NovuliSurvices are for informational and convenience purposes only. we cannot and do not guarantee the accuracy, completeness, or reliability of tool outputs. 
            </p>

            <div className="bg-blue-50 border-l-4 border-blue-500 p-6 rounded-r-2xl mb-10">
              <div className="flex gap-4">
                <FiInfo className="text-blue-500 shrink-0 mt-1" size={24} />
                <p className="text-blue-900 text-sm font-medium leading-relaxed m-0">
                  Tool outputs may contain errors, inaccuracies, or omissions. You should verify all results independently before relying on them for any business or professional decisions.
                </p>
              </div>
            </div>

            <section className="space-y-8">
              <div>
                <h2 className="text-2xl font-bold text-primary mb-4">1. No Professional Advice</h2>
                <p>
                  NovuliSurvices does not provide professional, legal, financial, or medical advice. The calculations, conversions, and analyses generated by our tools are based on general algorithms and may not account for specific legal or industry requirements applicable to you.
                </p>
              </div>

              <div>
                <h2 className="text-2xl font-bold text-primary mb-4">2. Tool-Specific Limitations</h2>
                <p>
                  Our SEO Audit, Background Removers, converters, and other utilities use various third-party libraries and AI models. These models are probabilistic in nature and can produce incorrect or unexpected results. Outputs should be treated as estimates rather than absolute facts.
                </p>
              </div>

              <div>
                <h2 className="text-2xl font-bold text-primary mb-4">3. Limitation of Liability</h2>
                <p>
                  In no event shall NovuliSurvices be liable for any direct, indirect, incidental, or consequential damages arising out of the use of or inability to use our tools, even if we have been advised of the possibility of such damages.
                </p>
              </div>

              <div>
                <h2 className="text-2xl font-bold text-primary mb-4">4. "As Is" Basis</h2>
                <p>
                  All tools and services are provided on an "as is" and "as available" basis without any warranties of any kind, either express or implied, including but not limited to warranties of merchantability or fitness for a particular purpose.
                </p>
              </div>
            </section>

            <div className="mt-16 pt-10 border-t border-border-light flex flex-col sm:flex-row gap-6">
              <Link href="/" className="bg-primary text-white px-8 py-4 rounded-xl font-bold text-center hover:bg-slate-800 transition-all shadow-lg">
                Return to Home
              </Link>
              <Link href="/contact" className="bg-bg-gray text-primary border border-border-light px-8 py-4 rounded-xl font-bold text-center hover:bg-white hover:border-accent transition-all">
                Contact Support
              </Link>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
